from __future__ import annotations

from typing import Protocol, runtime_checkable

from agent.soul.memory.domain import MemoryNetwork, SocialNodeRole
from agent.soul.memory.graph.base_node import BaseNode


@runtime_checkable
class GraphNodeStore(Protocol):
    def put(self, node: BaseNode) -> None: ...
    def get(self, node_id: str) -> BaseNode | None: ...
    def get_many(self, node_ids: list[str]) -> list[BaseNode]: ...
    def list_by_network(self, network: MemoryNetwork, *, limit: int = 50) -> list[BaseNode]: ...
    def list_by_interactor(
        self,
        interactor_id: str,
        role: SocialNodeRole | None = None,
        *,
        limit: int = 50,
    ) -> list[BaseNode]: ...
    def archive(self, node_id: str) -> None: ...
    def on_recall(self, node_id: str) -> None: ...
    def add_rehearsal(self, node_id: str) -> None: ...
    def get_by_life_event_id(self, life_event_id: str) -> BaseNode | None: ...
    def get_core_for_interactor(self, interactor_id: str) -> BaseNode | None: ...
    def query_by_fields(self, **kwargs) -> list[BaseNode]: ...
    def list_recent(self, memory_type: str | None = None, valence=None, network: MemoryNetwork | None = None, limit: int = 50) -> list[BaseNode]: ...
    def list_all(self, limit: int = 2000, network: MemoryNetwork | None = None) -> list[BaseNode]: ...
    def add_narrative_ref(self, node_id: str) -> None: ...
    def forget_scan(
        self,
        *,
        threshold: float,
        half_life_days: float,
        dry_run: bool,
    ) -> list[str]: ...
