class SpeakAction:
    OPEN_SESSION = "open_session"
    RECORD_DIALOGUE = "record_dialogue"
    CLOSE_SESSION = "close_session"
    OPEN_OUTBOUND = "open_outbound"
    INGEST_QUESTION = "ingest_question"
    DELIVER = "deliver"
    GENERATE = "generate"
    GENERATE_STREAM = "generate_stream"
    RUN_TURN = "run_turn"
    DRIVE_SNAPSHOT = "drive_snapshot"
    EVALUATE_DRIVE = "evaluate_drive"
    WORKING_MEMORY = "working_memory"
    DIALOGUE_STATE = "dialogue_state"
    TYPING_PULSE = "typing_pulse"
    SET_DELIVERY_MODE = "set_delivery_mode"
    DIRECTOR_SNAPSHOT = "director_snapshot"
    ENQUEUE_BREW = "enqueue_brew"
