"""对外接口：shared + ingress（入站）+ egress（出站）。"""

from .egress import (
    EmbeddingPort,
    LightweightReactEngine,
    PresenceReactOutbound,
    ReactAction,
    ReactActionCall,
    ReactActionExecutor,
    ReactStepResult,
    ShareFoldedPackage,
    SpeakInterface,
    SpeakInterfaceConfig,
    SpeakRequest,
    enqueue_capture_event,
    enqueue_share_event,
    fold_share_buffer,
    fold_share_queue,
    parse_action_field,
    share_intent_from_capture,
)
from .ingress import PresenceInterface, PresenceTriggerResult, apply_evolution_impulse
from .shared import (
    EVOLUTION_KINDS,
    CaptureEvent,
    CaptureKind,
    default_share_desire,
    evolution_hint,
)

__all__ = [
    "CaptureEvent",
    "CaptureKind",
    "EVOLUTION_KINDS",
    "EmbeddingPort",
    "LightweightReactEngine",
    "PresenceInterface",
    "PresenceReactOutbound",
    "PresenceTriggerResult",
    "ReactAction",
    "ReactActionCall",
    "ReactActionExecutor",
    "ReactStepResult",
    "SpeakInterface",
    "SpeakInterfaceConfig",
    "SpeakRequest",
    "ShareFoldedPackage",
    "apply_evolution_impulse",
    "default_share_desire",
    "enqueue_capture_event",
    "enqueue_share_event",
    "evolution_hint",
    "fold_share_buffer",
    "fold_share_queue",
    "parse_action_field",
    "share_intent_from_capture",
]
